name: Auto Comment @dependabot
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.REBASE_TOKEN }}
          pullRequestOpened: >
           @{{ author }} rebase
           @{{ author }} merge
