name: Broken Web Link Checker

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Broken Web Link Checker
    runs-on: ubuntu-latest

    steps:
      - name: Broken Web Link Checker
        uses: hashicorp/gh-action-check-broken-links@v1
        with:
          baseUrl: 'https://chaselab.netlify.app' 
          files: 'docs/*.mdx'
